DEFAULT_TASKS = [
    {
        "title": "Tell friends about Gift Fest",
        "description": "Share your invite link with friends and channels.",
        "category": "daily",
        "icon": "share",
        "reward_label": "+75 energy & lootbox",
        "reward_value": 75,
        "reward_unit": "energy",
        "progress_current": 0,
        "progress_target": 1,
        "state": "in_progress",
        "action": "start",
        "order": 1,
    },
    {
        "title": "Join Gift Fest",
        "description": "Enter the event and start collecting rewards.",
        "category": "daily",
        "icon": "gift",
        "reward_label": "+100 energy",
        "reward_value": 100,
        "reward_unit": "energy",
        "progress_current": 0,
        "progress_target": 1,
        "state": "in_progress",
        "action": "start",
        "order": 2,
    },
    {
        "title": "Merge gifts 40 times",
        "description": "Play through merges to unlock more energy.",
        "category": "daily",
        "icon": "merge",
        "reward_label": "+20 energy",
        "reward_value": 20,
        "reward_unit": "energy",
        "progress_current": 23,
        "progress_target": 40,
        "state": "in_progress",
        "action": "start",
        "order": 3,
    },
    {
        "title": "Invite 2 friends",
        "description": "Bring in new friends to grow the event reach.",
        "category": "daily",
        "icon": "friends",
        "reward_label": "+10 to the energy limit",
        "reward_value": 10,
        "reward_unit": "limit",
        "progress_current": 1,
        "progress_target": 2,
        "state": "in_progress",
        "action": "start",
        "order": 4,
    },
    {
        "title": "Open 10 gift boxes",
        "description": "Finish the set and claim your extra energy.",
        "category": "daily",
        "icon": "box",
        "reward_label": "+50 energy",
        "reward_value": 50,
        "reward_unit": "energy",
        "progress_current": 10,
        "progress_target": 10,
        "state": "ready",
        "action": "claim",
        "order": 5,
    },
]
