# Production environment overrides

services:
  mq:
    ports:
      - ${REDIS_PORT}:6379

  api:
    volumes:
      # For monitoring
      - /proc/cpuinfo:/proc/cpuinfo:ro
    ports:
      - ${API_PORT}:5000
    command: bash -c "cd /app && uv run uvicorn main:app --host 0.0.0.0 --port 5000 --proxy-headers"

  worker:
    command: bash -c "cd /app && uv run taskiq worker --app-dir /app tasks.broker:broker tasks.registry --workers 2 --log-level INFO"

  scheduler:
    command: bash -c "cd /app && uv run taskiq scheduler --app-dir /app tasks.scheduler:scheduler tasks.registry --log-level INFO"

  tg:
    ports:
      - ${TG_PORT}:80

  web:
    build:
      context: ../../web
      target: runner
    ports:
      - ${WEB_PORT}:3000
    command: ["npm", "start"]
