# Production environment overrides

services:
  mq:
    ports:
      - ${REDIS_PORT}:6379

  api:
    volumes:
      # For monitoring
      - /proc/cpuinfo:/proc/cpuinfo:ro
    ports:
      - ${API_PORT}:5000
    command: bash -c "cd /app && uv run uvicorn main:app --host 0.0.0.0 --port 5000 --proxy-headers"

  # jobs:
  #   image: ${PROJECT_NAME}/jobs
  #   build: ../../api
  #   restart: unless-stopped
  #   env_file: ../../.env
  #   environment:
  #     API: ${PROTOCOL}://${EXTERNAL_HOST}/api/
  #     WEB: ${PROTOCOL}://${EXTERNAL_HOST}/
  #   volumes:
  #     # For logs
  #     - ${DATA_PATH}/logs/jobs.err:/app/app.err
  #     - ${DATA_PATH}/logs/jobs.log:/app/app.log
  #     # For sitemap
  #     - ${DATA_PATH}/sitemaps:/data/sitemaps
  #     - ${DATA_PATH}/sitemap.xml:/data/sitemap.xml
  #     - ${DATA_PATH}/robots.txt:/data/robots.txt
  #   command: bash -c "cd /app && uv run python job.py"

  # tg:
  #   image: ${PROJECT_NAME}/tg
  #   build: ../../tg
  #   restart: unless-stopped
  #   env_file: ../../.env
  #   environment:
  #     API: ${PROTOCOL}://${EXTERNAL_HOST}/api/
  #     WEB: ${PROTOCOL}://${EXTERNAL_HOST}/
  #     TG: ${PROTOCOL}://${EXTERNAL_HOST}/tg/
  #   volumes:
  #     # For logs
  #     - ${DATA_PATH}/logs/tg.err:/app/app.err
  #     - ${DATA_PATH}/logs/tg.log:/app/app.log
  #   depends_on:
  #     - api
  #   ports:
  #     - ${TG_PORT}:80

  web:
    build:
      context: ../../web
      target: runner
    ports:
      - ${WEB_PORT}:3000
    command: bash -c "npm run build && npm start"
