# Development environment overrides (remote development stage server)

services:
  api:
    volumes:
      # For hot reload
      - ../../api/app:/app
    command: bash -c "cd /app && uv run uvicorn main:app --host 0.0.0.0 --port 5000 --proxy-headers --reload"

  web:
    build:
      context: ../../web
      target: development
    volumes:
      # For hot reload in development
      - ../../web:/app
      # Exclude to avoid conflicts and cache issues
      - /app/node_modules
      - /app/.next
      - /app/.swc
    command: npm run dev
