# Local development overrides

services:
  mq:
    ports:
      - 6379:6379

  db:
    image: mongo:7.0
    restart: unless-stopped
    env_file: ../../.env
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ${DATA_PATH}/db:/data/db
      - ../mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf

  api:
    depends_on:
      - db
    volumes:
      # For hot reload
      - ../../api/app:/app
    command: bash -c "cd /app && python -m uvicorn main:app --host 0.0.0.0 --port 5000 --proxy-headers --reload"
    # healthcheck:
    #   test: "curl --fail http://0.0.0.0:5000/"
    #   interval: 1s
    #   timeout: 1s
    #   start_period: 180s
    #   retries: 180

  worker:
    depends_on:
      - db
    volumes:
      # For hot reload
      - ../../api/app:/app

  scheduler:
    depends_on:
      - db
    volumes:
      # For hot reload
      - ../../api/app:/app

  tg:
    profiles:
      - tg
    volumes:
      # For hot reload
      - ../../tg:/app
    command: bash -c "cd /app && uv run uvicorn main:app --host 0.0.0.0 --port 80 --proxy-headers --reload"

  web:
    build:
      context: ../../web
      target: development
    volumes:
      # For hot reload in development
      - ../../web:/app
      # Exclude to avoid conflicts and cache issues
      - /app/node_modules
      - /app/.next
      - /app/.swc
    command: npm run dev

  server:
    image: nginx:1.29
    restart: unless-stopped
    env_file: ../../.env
    volumes:
      - ../nginx/local.conf:/etc/nginx/nginx.conf
      - ${DATA_PATH}/load:/load
      # For sitemap
      - ${DATA_PATH}/sitemaps:/data/sitemaps
      - ${DATA_PATH}/sitemap.xml:/data/sitemap.xml
      - ${DATA_PATH}/robots.txt:/data/robots.txt
    depends_on:
      - api
      # - jobs
      - web
    ports:
      - ${EXTERNAL_PORT}:80
