services:
  mq:
    ports:
      - 6379:6379

  db:
    image: mongo:7.0
    restart: unless-stopped
    env_file: ../../.env
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ${DATA_PATH}/db:/data/db
      - ../mongo/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf

  api:
    depends_on:
      - db
    # command: bash -c "cd /app && uv run uvicorn main:app --host 0.0.0.0 --port 5000 --proxy-headers"
    command: make test

  web:
    depends_on:
      - api
    # command: bash -c "npm run build && npm start"
    command: bash -c "npm i && node_modules/.bin/eslint . --ext .js --ext .jsx"
